name: Run Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Release Please Action
        uses: googleapis/release-please-action@v2
        id: release
        with:
          command: manifest
          token: ${{ secrets.TOKEN }}
          default-branch: main