name: Run Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Run Release Please Action
      #   uses: googleapis/release-please-action@v2
      #   with:
      #     command: manifest
      #     token: ${{ secrets.TOKEN }}
      #     default-branch: main

      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: "simple"
          token: ${{ secrets.TOKEN }}
          # optional. customize path to release-please-config.json
          # config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          # manifest-file: .release-please-manifest.json